# Generated by Django 4.0.5 on 2022-06-30 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clientId', models.AutoField(primary_key=True, serialize=False, verbose_name='CLIENTID')),
                ('firstName', models.CharField(max_length=25, verbose_name='FIRSTNAME')),
                ('lastName', models.CharField(max_length=30, verbose_name='LASTNAME')),
                ('email', models.EmailField(max_length=254, verbose_name='EMAIL')),
                ('registratedOn', models.DateTimeField(verbose_name=datetime.datetime(2022, 6, 30, 16, 36, 5, 753082))),
                ('phoneNumber', models.CharField(max_length=8)),
                ('country', models.CharField(max_length=38, verbose_name='COUNTRY')),
                ('state', models.CharField(max_length=34, verbose_name='STATE')),
                ('city', models.CharField(max_length=34, verbose_name='CITY')),
                ('place', models.CharField(max_length=34, verbose_name='PLACE')),
                ('adress', models.CharField(max_length=34, verbose_name='ADRESS')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medias', verbose_name='PRODUCTOIMAGEN'),
        ),
    ]
